---
title: "About"
---

I am statistician working full-time as Data Scientist at
[Grupo San Cristóbal](https://www.gruposancristobal.com.ar/), a company in
the insurance and financial industry in Argentina.

Until very recently, I was full-time dedicated to study and research thanks to 
a Doctoral Fellowship by CONICET (Argentina). My place of work was at IMASL in 
San Luis, Argentina. I'm still a part-time PhD student.

### Why Statistics?

I’ve always felt curious about so many things that I couldn't pick just one.
So I studied Statistics. At that time I felt that something like statistics would
give me the chance to work (and learn) with different problems from different 
fields and, consequently, I could chose to specialize in a particular field later
in my career.

Nowadays, I am not only very happy to have chosen what I chose, but also eager 
to keep learning. Hopefully, one day I will be able to contribute with my share
to the community and return something of all I have been taught.

### Interests

* Statistical learning
* Bayesian statistics
* Programming languages
* Exploratory data analysis
* Data visualization

### Education

* PhD in Statistics - Universidad Nacional de Rosario - 2024 (expected)
* BSc in Statistics - Universidad Nacional de Rosario - 2019