---
title: "What I read 📖" 
toc: false
---

And what I want to read...

---

If you want to know why I created this list, check [I'm starting a reading list!](posts/2024-02-01_starting_a_reading_list/index.qmd).

If you want my opinion on some title, make any recommendation, or simply discuss about some book, just reach me out by e-mail.

**NOTE** This is not fully done yet. 

---

## In progress

Nothing for now!

## Non-technical

### 2024

- [Rosario: La historia detrás de la mafia narco que se adueñó de la ciudad](https://www.penguinlibros.com/ar/biografias/336529-libro-rosario-9789500769815).<br> Germán de los Santos, Hernán Lascano (2023)
- [El Nudo: Por qué el conurbano bonaerense modela la política argentina](https://www.planetadelibros.com/libro-el-nudo/375124).<br> Carlos Pagni (2023)

### 2023

- [Gallardo Eterno: Últimos 4 años y balance de una historia hermosísima](https://www.penguinlibros.com/ar/tiempo-libre/327302-libro-gallardo-eterno-9789877353242).<br> Diego Borinsky (2023)
- [Téngase Presente: El mundo según Carlos Maslatón](https://tienda.planetadelibros.com.ar/products/tengase-presente). <br> Carlos Maslatón (2023)
- [Born](https://www.google.com.ar/books/edition/BORN/ViL8CAAAQBAJ).<br> Maria O' Donnell (2015)
- [El Jefe: Vida y Obra de Carlos Saúl Menem](https://gabrielacerruti.com.ar/portfolio_page/el-jefe-vida-y-obra-de-carlos-saul-menem/). <br> Gabriela Cerruti (1993)
- [La ciencia de las (buenas) ideas](https://sigloxxieditores.com.ar/libro/la-ciencia-de-las-buenas-ideas/). <br> Diego Golombek (2022)

### 2022

- [Repartir el pastel](https://www.google.com.ar/books/edition/Repartir_el_pastel/q5bQEAAAQBAJ). <br> Barry Nalebuff (2022)
- [En Corea del Norte](https://www.penguinlibros.com/ar/economia-politica-y-actualidad/157126-libro-en-corea-del-norte-9789873752964). <br> Florencia Grieco (2018)
- [El fútbol según Bielsa](https://www.penguinlibros.com/ar/tiempo-libre/258875-libro-el-futbol-segun-bielsa-9789877352597). <br> Salim Lamrani (2021)
- [El mundo ha vivido equivocado y otros cuentos](https://www.planetadelibros.com.ar/libro-el-mundo-ha-vivido-equivocado-ne/355260). <br> Roberto Fontanarrosa (TBD)


### 2019

- [Gallardo Monumental](https://www.penguinlibros.com/ar/tiempo-libre/162489-ebook-gallardo-monumental-9789877351248). <br> Diego Borinsky (2015)
- [Gallardo Eterno](https://www.penguinlibros.com/ar/biografias/162765-libro-gallardo-recargado-9789877352221). <br> Diego Borinsky (2019)
- [En defensa del modelo](https://www.penguinlibros.com/ar/economia-politica-y-actualidad/145501-libro-en-defensa-del-modelo-9789500758437). <br> Guillermo Moreno (2017)
- [El último teorema de Fermat](https://www.cianavierailimitada.com/productos/el-ultimo-teorema-de-fermat-simon-singh/). <br> Simon Singh
- [You Look Like a Thing and I Love You](https://books.google.com.ar/books/about/You_Look_Like_a_Thing_and_I_Love_You.html?id=9kOezQEACAAJ). <br> Janelle Shane (2019)
- [Big data](https://www.google.com.ar/books/edition/_/wm7ADwAAQBAJ). <br> Walter Sosa Escudero (2019)

### 2018

- [Qué es (y qué no es) la estadística](https://www.google.com.ar/books/edition/_/lrIDoQEACAAJ). <br> Walter Sosa Escudero (2014)
- [¡7500 millones de personas! ¿qué es y para qué sirve la demografía?](https://sigloxxieditores.com.ar/libro/7500-millones-de-personas/). <br> Jorge Paz (2018)
- [El barman científico](https://sigloxxieditores.com.ar/libro/el-barman-cientifico/). <br> Facundo Di Génova (2016).
- [El personal trainer científico](https://sigloxxieditores.com.ar/libro/el-personal-trainer-cientifico/). <br> Germán Laurora (2013)

### Earlier...

- [Una realidad aparte](https://books.google.com.ar/books/about/Una_realidad_aparte.html?id=Gc9XxgEACAAJ). <br> Carlos Castañeda (1974)
- [Ficciones](https://books.google.com.ar/books?id=LY9dAAAAMAAJ). <br> Jorge Luis Borges (1944)


## Technical

I rarely read statistics and technical books from cover to cover, so I'm not going to 
pretend that I've completely covered all of the books listed here.
Typically, I focus on specific chapters that are of my interest, although there are instances
where I read the entire book. Additionally, I often find myself revisiting some of these
books for a second read.

- [Functional programming in R](https://link.springer.com/book/10.1007/978-1-4842-2746-6).<br> Thomas Mailund (2017)
- [Engineering production-grade Shiny apps](https://www.routledge.com/Engineering-Production-Grade-Shiny-Apps/Fay-Rochette-Guyader-Girard/p/book/9780367466022). <br> Colin Fay, Sébastien Rochette, Vincent Guyader and Cervan Girard (2022)
- [Advanced R](https://www.routledge.com/Advanced-R-Second-Edition/Wickham/p/book/9780815384571). <br> Hadley Wickham (2019)
- [Extending R](https://www.routledge.com/Extending-R/Chambers/p/book/9781498775717). <br> John M. Chambers (2016)
- [R Graphics](https://www.routledge.com/R-Graphics-Third-Edition/Murrell/p/book/9780367780692). <br> Paul Murrell (2019)
- [Crafting Interpreters](https://craftinginterpreters.com/). <br> Robert Nystrom (2021)
- [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/). <br> Andrew Gelman, John Carlin, Hal Stern, David Dunson, Aki Vehtari, and Donald Rubin (2013)
- [The Elements of Statistical Learning](https://link.springer.com/book/10.1007/978-0-387-84858-7)
- [Computer Age Statistical Inference](https://www.cambridge.org/core/books/computer-age-statistical-inference/E32C1911ED937D75CE159BBD21684D37). <br> Bradley Efron and Trevor Hastie (2016)
- [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/). <br> Richard McElreath (2020)
- [Regression and Other Stories](https://www.cambridge.org/highereducation/books/regression-and-other-stories/DD20DD6C9057118581076E54E40C372C#overview). <br> Andrew Gelman, Jennifer Hill, and Aki Vehtari (2020)
- [Data Analysis Using Regression and Multilevel/Hierarchical Models](http://www.stat.columbia.edu/~gelman/arm/). <br> Andrew Gelman, Jennifer Hill (2006)
- [Introduction to Probability](https://www.routledge.com/Introduction-to-Probability-Second-Edition/Blitzstein-Hwang/p/book/9781138369917). <br> Joseph K. Blitzstein and Jessica Hwang (2019)
- [Bayesian Modeling and Computation in Python](https://www.routledge.com/Bayesian-Modeling-and-Computation-in-Python/Martin-Kumar-Lao/p/book/9780367894368). <br> Osvaldo A. Martin, Ravin Kumar, and Junpeng Lao (2022)
- [Bayes Rules!](https://www.routledge.com/Bayes-Rules-An-Introduction-to-Applied-Bayesian-Modeling/Johnson-Ott-Dogucu/p/book/9780367255398). <br> Alicia A. Johnson, Miles Q. Ott, and Mine Dogucu (2022)
- ...
