---
title: "GSOC 2021: Final evaluation"
date: 2021-08-17
output:
  distill::distill_article:
    self_contained: false
description: |
  Final post about Google Summer of Code 2021. This post sums up my
  contributions to the Bambi library during the ten weeks of this program.
editor_options:
  chunk_output_type: console
---

```{r plots-setup, echo=FALSE}
knitr::opts_chunk$set(fig.align = "center", out.width = "95%")
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

In this short blogpost, I'm going to summarize my contributions to the Bambi
library during this Google Summer of Code.

GSoC has been great. I've learnt so much during the past weeks. And I'm
obviously eager to keep learning and doing stuff with 
[Bambi](https://bambinos.github.io/bambi) in the future. The following is a
summary of what we were able to achieve during these time of code:

* Implemented new default priors [#360](https://github.com/bambinos/bambi/pull/360), [#385](https://github.com/bambinos/bambi/pull/385).
* Added new Student-T family [#367](https://github.com/bambinos/bambi/pull/367).
* Added new Beta family [#368](https://github.com/bambinos/bambi/pull/368).
* Implemented predictions [#372](https://github.com/bambinos/bambi/pull/372).
* Improved internal model specification by splitting it into smaller and composable 
classes [#366](https://github.com/bambinos/bambi/pull/366).
* Added the new Binomial family [#386](https://github.com/bambinos/bambi/pull/386). 
This also implied [some changes](https://github.com/bambinos/formulae/pull/48) 
in its sibling project, [formulae](https://bambinos.github.io/formulae).

This, with many other smaller changes or improvements that you can find 
[here](https://github.com/bambinos/bambi/commits?author=tomicapretto) were 
included in [Bambi 0.6.0](https://pypi.org/project/bambi/0.6.0/).

On the other hand, the items on my original proposal that left to do are 
multinomial regression and ordered categorical terms. I've started to do some 
work on the formulae side, but these features require a more involved work in 
Bambi, and thus it is left for future contributions.

To conclude, I want to thank Google for having such an amazing program and 
everyone who contributed or helped me to contribute to Bambi. Specially, I want 
to recognize the the work of my mentors Ravin Kumar and Thomas Wiecki, and my 
director Osvaldo Martin for all the support, feedback, and work 
during this program.